In [2]:
import numpy as np
import pandas as pd

df_cleaned = pd.read_csv("../../data/cleaned/Metallic Glass Transition Data/Metallic_Glass_Forming_with_features_CLEANED.csv")
df_cleaned.head()

,Material compositions,Trg,Density_composition_average,IsBoron_composition_average,IsDBlock_composition_average,NdValence_composition_average,NValance_composition_average,HeatVaporization_max_value,BoilingT_difference,HeatVaporization_difference,...,Nb,Mg,Gd,La,Zr,P,Cr,Ni,Ag,C
0,Ag10Cu35Zr55,0.534,0.579069,-0.5856,1.029882,0.589536,0.217571,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,55.0,0.0,0.0,0.0,10.0,0.0
1,Ag10Cu50Zr40,0.608,0.748401,-0.5856,1.029882,1.176250,0.653969,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,10.0,0.0
2,Ag10Cu55Zr35,0.609,0.804845,-0.5856,1.029882,1.371822,0.799435,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,10.0,0.0
3,Ag20Cu40Zr40,0.577,0.821973,-0.5856,1.029882,1.176250,0.653969,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,20.0,0.0
4,Ag35Ca65,0.515,-0.860992,-0.5856,-0.998961,-0.437214,-0.613663,-1.684370,-1.368929,-1.228445,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,0.0

In [3]:
import pycaret
pycaret.__version__

'3.3.2'

In [4]:
from pycaret.regression import *
# Keep "Material compositions" column for later
material_compositions = df_cleaned.iloc[:, 0]

df_features = df_cleaned.iloc[:, 1:]
s = setup(data=df_features, target="Trg", normalize=True, train_size=0.8, session_id=123)
# s = setup(data=df_features, target="Trg", session_id=123)

# s = setup(
#     data=df_features,
#     target='Trg',
#     session_id=123,
#     train_size=0.7,
#     normalize=True,
#     remove_multicollinearity=True,
#     multicollinearity_threshold=0.90,
#     low_variance_threshold=0.05,
#     fold=10,
#     n_jobs=-1
# )

# s = setup(
#     data=df_features, 
#     target="Trg", 
#     session_id=123,
#     remove_multicollinearity=True,
#     multicollinearity_threshold=0.7,
#     transform_target=True,
#     normalize=True
# )

# s = setup(
#     data=df_features,
#     target="Trg",
#     session_id=123,
    
#     # Preprocessing
#     remove_multicollinearity=True,
#     multicollinearity_threshold=0.7,
#     normalize=True,              # important for PCA
#     transform_target=True,       # optional: stabilizes skewed target
    
#     n_jobs=-1
# )


# feature_selection=True,
# feature_selection_threshold=0.8,

# s = setup(
#     data=df_features,
#     target="Trg",
#     low_variance_threshold=1e-12,
#     normalize=True,
#     fold=5,
#     train_size=0.8,
#     verbose=0,
#     n_jobs=-1,
#     session_id=3131,
#     remove_multicollinearity=True,
#     multicollinearity_threshold=0.7,
#     transform_target=True,
# )

# s = setup(
#     data=df_features,
#     target="Trg",
#     low_variance_threshold=1e-4,
#     normalize=True,
#     fold=10,
#     train_size=0.8,
#     n_jobs=-1,
#     session_id=3131,
#     remove_multicollinearity=True,
#     multicollinearity_threshold=0.8,
#     transform_target=True,
#     remove_outliers=True,
#     outliers_threshold=0.01,
# )

# s = setup(
#     data=df_features,
#     target="Trg",
#     low_variance_threshold=1e-4,
#     normalize=True,
#     fold=10,
#     train_size=0.8,
#     n_jobs=-1,
#     session_id=3131,
#     remove_multicollinearity=True,
#     multicollinearity_threshold=0.7,
#     transform_target=True,
#     remove_outliers=True,
#     outliers_threshold=0.05,
#     polynomial_features=True,
# )

# s = setup(
#     data=df_features,
#     target="Trg",
#     normalize=True,
#     fold=10,
#     train_size=0.8,
#     n_jobs=-1,
#     session_id=3131,
#     remove_multicollinearity=True,
#     multicollinearity_threshold=0.7,
#     transform_target=True,
#     # feature_selection_method='classic',  # or 'boruta', 'sequential',
#     verbose=0
# )

In [5]:
best = compare_models(n_select=3)

In [6]:
best

[ExtraTreesRegressor(n_jobs=-1, random_state=123),
 RandomForestRegressor(n_jobs=-1, random_state=123),
 LGBMRegressor(n_jobs=-1, random_state=123)]

In [8]:
# et_model = best[0]

# plot_model(et_model, plot="rfe")

In [9]:
tuned_models = [
    tune_model(model) for model in best
]

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [10]:
# et = create_model('et', return_train_score=True, max_depth=20, n_estimators=50, min_samples_split=2)

In [11]:
# plot_model(et, plot="residuals")

In [12]:
et_model = create_model('et', return_train_score=True)

In [13]:
rand_search = {
    'n_estimators': (100, 600),
    'max_depth': (5, 20),
    'min_samples_split': (2, 20),
    'min_samples_leaf': (1, 10),
    'max_features': (0.5, 1.0),
    'bootstrap': [True, False]
}

tuned_random = tune_model(
    et_model,
    optimize='R2',
    n_iter=50,                 # 50 random trials
    search_library='optuna',
    search_algorithm='tpe',
    custom_grid=rand_search
)

Initiated  . . . . . . . . . . . . . . . . . .                   14:55:49
Status     . . . . . . . . . . . . . . . . . .  Searching Hyperparameters
Estimator  . . . . . . . . . . . . . . . . . .      Extra Trees Regressor

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

KeyboardInterrupt:

In [19]:
best_params = tuned_random.get_params()
# Narrow ranges for grid search based on best params
grid_search = {
    'n_estimators': [max(50, best_params['n_estimators']-100), best_params['n_estimators'], best_params['n_estimators']+100],
    'max_depth': [max(3, best_params['max_depth']-3), best_params['max_depth'], best_params['max_depth']+3],
    'min_samples_split': [max(2, best_params['min_samples_split']-3), best_params['min_samples_split'], best_params['min_samples_split']+3],
    'min_samples_leaf': [max(1, best_params['min_samples_leaf']-2), best_params['min_samples_leaf'], best_params['min_samples_leaf']+2],
    'max_features': [max(0.3, best_params['max_features']-0.1), best_params['max_features'], min(1.0, best_params['max_features']+0.1)],
    'bootstrap': [best_params['bootstrap']]
}

In [20]:
tuned_grid = tune_model(
    et_model,
    optimize='R2',
    search_library='scikit-learn',
    search_algorithm='grid',
    custom_grid=grid_search
)

Fitting 10 folds for each of 243 candidates, totalling 2430 fits

In [22]:
tuned_grid

ExtraTreesRegressor(max_depth=20, max_features=0.5, n_estimators=600, n_jobs=-1,
                    random_state=3131)

In [25]:
best_params = tuned_grid.get_params()
# Narrow ranges for grid search based on best params again
grid_search_2 = {
    'n_estimators': [max(50, best_params['n_estimators']-100), best_params['n_estimators'], best_params['n_estimators']+100],
    'max_depth': [max(3, best_params['max_depth']-3), best_params['max_depth'], best_params['max_depth']+3],
    'min_samples_split': [max(2, best_params['min_samples_split']-3), best_params['min_samples_split'], best_params['min_samples_split']+3],
    'min_samples_leaf': [max(1, best_params['min_samples_leaf']-2), best_params['min_samples_leaf'], best_params['min_samples_leaf']+2],
    'max_features': [max(0.3, best_params['max_features']-0.1), best_params['max_features'], min(1.0, best_params['max_features']+0.1)],
    'bootstrap': [best_params['bootstrap']]
}

In [26]:
tuned_grid_2 = tune_model(
    et_model,
    optimize='R2',
    search_library='scikit-learn',
    search_algorithm='grid',
    custom_grid=grid_search_2
)

Fitting 10 folds for each of 243 candidates, totalling 2430 fits